# Generated by Django 4.1.3 on 2022-11-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0002_alter_comanda_is_editavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocomanda',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
